L_PAINTABLE_AREA = 'Paintable Area'
L_DECALS = 'Decals'
L_MASKS = 'Masks'
L_PIT_STUFF = 'Pit Stuff'
L_CARBON_FIBER = 'Carbon Fiber'
L_CARBON_FIBER_PATTERN_LEFT = 'Carbon Fiber Pattern Left'
L_CARBON_FIBER_PATTERN_RIGHT = 'Carbon Fiber Pattern Right'
L_PAINT = 'Paint'
L_CAR_PATTERNS = 'Car Patterns'
L_CUSTOM_PATTERN = 'Custom Pattern'
L_SPEC_MAP = 'Spec Map'
L_TURN_OFF_BEFORE_EXPORT = 'Turn Off Before Exporting TGA'
L_META = 'META'

L_RED_MASK = 'Paint Red Mask'
L_RED_SPEC = 'Spec Red Mask'
L_RED_SPEC_PATTERN = 'Spec Red Mask Pattern Base'

L_GREEN_MASK = 'Paint Green Mask'
L_GREEN_SPEC = 'Spec Green Mask'
L_GREEN_SPEC_PATTERN = 'Spec Green Mask Pattern Base'

L_BLUE_MASK = 'Paint Blue Mask'
L_BLUE_SPEC = 'Spec Blue Mask'
L_BLUE_SPEC_PATTERN = 'Spec Blue Mask Pattern Base'

L_DECAL_SPEC = 'Spec Decal Mask'

L_CF_LEFT_MASK = 'Left Carbon Fiber'
L_CF_LEFT_SPEC = 'Spec Left Carbon Fiber'
L_CF_RIGHT_MASK = 'Right Carbon Fiber'
L_CF_RIGHT_SPEC = 'Spec Right Carbon Fiber'


C_RED = 'Red Channel - Auto'
C_GREEN = 'Green Channel - Auto'
C_BLUE = 'Blue Channel - Auto'
C_DECAL_ALPHA = 'Decal Alpha Channel - Auto'
C_CARBON_LEFT = 'Carbon Fiber Left Channel - Auto'
C_CARBON_RIGHT = 'Carbon Fiber Right Channel - Auto'
